name: Site lint & links
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install htmlhint
        run: |
          npm i -g htmlhint
      - name: Run htmlhint
        run: |
          htmlhint --config .htmlhintrc || true
      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --max-concurrency 8
            --retry-wait-time 2
            --timeout 20
            --exclude-mail
            *.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
